### ISSUE TITLE
Filesystem queue directory creation with multiple servers

### ISSUE THREAD

**Issue by displacedaussie** [zopefoundation/Products.MailHost#2]
For an environment with Plone instances running on different servers, the MailHost queue directory (as expected) is initially created only on the server handling the request when the queue directory is set.

When viewing the MailHost on a different instance, attempting to start a queue process thread displays an error:

```
n/a - /var/mail/plonesite is not a maildir - please verify your configuration
```

If [x] mail queue and a Queue directory is set, it would be good if the triggering of the queue processor thread also created the maildir if it didn't exist.

Otherwise the mail queue directory needs to be created manually on each of the other servers.

**Comment by dataflake** [comment]
This is a safety issue. Changing a setting in the ZMI should never just blindly create items on the host filesystem, be it folders or files. An administrator should make the conscious decision to create that folder.

In cbee9d5784ec23fd7497ec7fb41349e1f123803c I prevent ZMI blowups for those cases where the folder isn't acceptable.
