### ISSUE TITLE
Line ending-related test failures under Python 2.7

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Products.MailHost#37]
It looks like #36 was never tested under Python 2.7 so now there are line ending-related failures. Travis CI is broken for us right now, but I would expect anyone creating a PR to run `bin/tox` in the development sandbox to make sure all supported Python versions are tested.

@1letter Please revisit the code on the `master` branch and fix those test failures. You can run all tests in your sandbox with `bin/tox`, or just the Python 2.7 tests with `bin/tox -epy27`.

**Comment by 1letter** [comment]
@dataflake I have create a PR. I hope the Travis CI is now not broken.

**Comment by dataflake** [comment]
Travis CI does not work at all right now. You must run tox manually. If there are no failures in your local environment the code is ready for review.

**Comment by 1letter** [comment]
@dataflake my local run of bin/tox does not show errors
![console](https://user-images.githubusercontent.com/11072000/105138447-2dfd6280-5af5-11eb-9d9c-05e9b85de5f7.png)

**Comment by mauritsvanrees** [comment]
I do fear this means that the original problem is still there on Python 2.7. But it may be tricky to fix, as I guess the email policies we use are not available on Python 2.
Anyway, I confirm the PR fixes the tests.
