### ISSUE TITLE
queing without sending (for specific MailHost)

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Products.MailHost#42]
I know this is an already solved issue (#14), but as far as I understand, setting the environment variable would affect all MailHost objects in all instances of a Zope installation.

In my current case I would like to have a separate MailHost in a Zope instance for sending a newsletter, without it sending all Email at once. So I figured I could just let the MailHost do the queueing and send the queued mails later using some batching mechanism. This behaviour should only affect this specific MailHost.

Or maybe there is already a solution which I missed?

**Comment by d-maurer** [comment]
Georg Pfolz wrote at 2022-3-18 12:15 -0700:
>I know this is an already solved issue (#14), but as far as I understand, setting the environment variable would affect all MailHost objects in all instances of a Zope installation.
>
>In my current case I would like to have a separate MailHost in a Zope instance for sending a newsletter, without it sending all Email at once. So I figured I could just let the MailHost do the queueing and send the queued mails later using some batching mechanism. This behaviour should only affect this specific MailHost.
>
>Or maybe there is already a solution which I missed?

You can control everything via `MailHost` parameters or
`send` parameters -- with the exception of the envvar
`MAILHOST_QUEUE_ONLY`. The envvar affects all mail hosts (with
`smtp_queue == True`) in the instance.

In particula, you have:

 `send` parameter `immediate` (default "False"): "True" means
   to send the message immediately, not at transaction `commit`

 `MailHost` parameter `smtp_queue` and `smtp_queue_directory`:
   deliver the message to a maildir queue directory (the directory must have
   been set up externally -- this can be done with a function
   from `zope.sendmail`)
   A queue processor thread to transfer the messages from
   the maildir to the mail server is started automatically, unless
   the envvar `MAILHOST_QUEUE_ONLY` has a non empty value.
   In the latter case, a queue processor must be run externally.

 If `immediate` is `False` and `smtp_queue` is `False`, the
 message is delivered to the mail server at transaction commit.

**Comment by georgpfolz** [comment]
Thank you! I wasn't aware that parameters could be sent to the MailHost!

Here's how that could apply to my use-case:

- I set an empty value for `MAILHOST_QUEUE_ONLY`
- I set `immediate` `False` and  and `smtp_queue` `False` as default for most of my MailHosts
- I set an `smtp_queue` value for the MailHost dedicated to the newsletter: the queue would have to be processed by an external process.

Is this default configuration safe? I had bad experiences in the past when not using a mail queue: some mails just didn't get sent at all. But maybe that's different when `immediate` is `False` and the mail is only delivered at transaction commit?

What happens with not queued emails that cannot be sent for some reason?

**Comment by d-maurer** [comment]
Georg Pfolz wrote at 2022-3-18 13:53 -0700:
>Here's how that could apply to my use-case:
>
>- I set an empty value for `MAILHOST_QUEUE_ONLY`

If you want an external queue processor, you must use a **NON EMPTY** value

>- I set `immediate` `False` and  and `smtp_queue` `False` as default for most of my MailHosts
>- I set an `smtp_queue` value for the MailHost dedicated to the newsletter: the queue would have to be processed by an external process.
>
>Is this default configuration safe?

Should be safe.

>I had bad experiences in the past when not using a mail queue: some mails just didn't get sent at all.

When `immediate` is "False", the message is sent only when the transaction
is committed; the message is discarded when the transaction is aborted.

Even when the message is sent, errors (e.g. wrong email address) can prevent
the message to reach the destination.


>What happens with not queued emails that cannot be sent for some reason?

Delivery for those emails is prepared in a pre commit hook;
errors detected by the mail server lead to a transaction abort.
In the real commit, the delivery is terminated. Errors which
happen after this point are handled by the mail system
(usually an error message is sent to the "SMTP From" address
(not to be confused with the "message From" address).

**Comment by georgpfolz** [comment]
Thank you very much for the clarifications! That's very helpful!

**Comment by icemac** [comment]
@georgpfolz Is your question answered, so the issue can be closed?

**Comment by georgpfolz** [comment]
Yes, thank you, you can close it, I have all the informations I need!

For the time being, I will go another route: solving the batching problem before commiting the mail sendings, as the "system" solution seems a bit tricky and needs to be tested before unleashing it on my production instances.

Maybe you might consider implementing a parameter for the MailHost to this effect (sending the emails to the spool directory without starting the queue processor) at a later time, this would be a handy feature.
