### ISSUE TITLE
Port to Python 3 or make it optional

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.MailHost#6]
The following packages depend on `Products.MailHost`:

- [ ] zopefoundation/Products.GenericSetup
- [ ] zopefoundation/Products.CMFCore

This requires a Python 3 port of this package or it has to be made optional in all places where it is needed.

Needed for Python 3 port:

- [ ] #5 'email' module expects native 'str' in both Python 2.x and 3.x :(

**Comment by dataflake** [comment]
https://github.com/zopefoundation/Products.GenericSetup/pull/48 fixes the GenericSetup dependency

**Comment by dataflake** [comment]
633bd470be2162dda0ab364e28b0b95d342fb6fa fixes Python 3 compatibility (and thus this issue)
